DelaJob-Site-MVC/WebApplicationDelaJob/WebApplicationDelaJob/Models/Cadastro.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationDelaJob.Models
{
    public class Cadastro
    {
        public String email { get; set; }
        public String nome { get; set; }
        public String senha { get; set; }
    }
}

DelaJob-Site-MVC/WebApplicationDelaJob/WebApplicationDelaJob/Models/Contato.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationDelaJob.Models
{
    public class Contato
    {
        public String email { get; set; }
        public String nome { get; set; }
        public String assunto { get; set; }
        public String telefone { get; set; }
        public String mensagem { get; set; }
    }
}

DelaJob-Site-MVC/WebApplicationDelaJob/WebApplicationDelaJob/Models/ErrorViewModel.cs
using System;

namespace WebApplicationDelaJob.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DelaJob-Site-MVC/WebApplicationDelaJob/WebApplicationDelaJob/Models/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationDelaJob.Models
{
    public class Login
    {
        public String email { get; set; }
        public String senha { get; set; }
    }
}

DelaJob-Site-MVC/WebApplicationDelaJob/WebApplicationDelaJob/Controllers/CadastroController.cs
using WebApplicationDelaJob.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationDelaJob.Controllers
{
    public class CadastroController : Controller
    {
        public IActionResult Cadastro()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastro(CadastroController cad)
        {
            return RedirectToAction("Cadastro");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DelaJob-Site-MVC/WebApplicationDelaJob/WebApplicationDelaJob/Controllers/ContatoController.cs
using WebApplicationDelaJob.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationDelaJob.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Contato()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contato(ContatoController cont)
        {
            return RedirectToAction("Contato");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DelaJob-Site-MVC/WebApplicationDelaJob/WebApplicationDelaJob/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplicationDelaJob.Models;

namespace WebApplicationDelaJob.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DelaJob-Site-MVC/WebApplicationDelaJob/WebApplicationDelaJob/Controllers/LoginController.cs
using WebApplicationDelaJob.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationDelaJob.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginController log)
        {
            return RedirectToAction("Login");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DelaJob-Site-MVC/WebApplicationDelaJob/WebApplicationDelaJob/Controllers/SobreController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationDelaJob.Controllers
{
    public class SobreController : Controller
    {
        public IActionResult Sobre()
        {
            return View();
        }
    }
}

DelaJob-Site-MVC/WebApplicationDelaJob/WebApplicationDelaJob/Controllers/VagasController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationDelaJob.Controllers
{
    public class VagasController : Controller
    {
        public IActionResult Vagas()
        {
            return View();
        }
    }
}

DelaJob-Site-MVC/WebApplicationDelaJob/WebApplicationDelaJob/Views/Cadastro/Cadastro.cshtml
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <title>DelaJob - Cadastro</title>
</head>
<body>
    
    <!-- Card cadastro: -->
    <div class="mt-5">

        <div class="text-center">
            <h1 style="color: rgb(148, 84, 180);">Cadastre-se</h1>
        </div>

        <div class="card mb-5" style="width: 18rem; margin: 0 auto; float: none;">
            <div class="card-body" style="background-color: rgb(227, 229, 231);">
                <form>
                    <div class="form-group">
                        <label for="Nome" class="lead">Nome Completo:</label><br>
                        <input type="text" name="Nome" id="Nome" class="form-control" aria-describedby="textHelp" required>
                    </div>
                    <div class="form-group">
                        <label for="E-mail" class="lead">E-mail:</label><br>
                        <input type="email" name="E-mail" id="E-mail" class="form-control" aria-describedby="emailHelp" required>
                    </div>
                    <div class="form-group">
                        <label for="Senha1" class="lead">Senha:</label><br>
                        <input type="password" id="Senha1" name="Senha" class="form-control" required>
                    </div>

                    <div class="text-center">
                        <button type="submit" class="btn text-light w-75" style="background-color: rgb(148, 84, 180); font-size: 25px; border-radius: 10px;">Cadastrar</button>
                        <p class="lead text-muted mt-3 mb-0" style="font-size: 14px;">Já tem cadastro?</p>
                        <a class="card-link mt-2" style="color: rgb(148, 84, 180);" href="#"><h2 class="lead">Login</h2></a>
                    </div>
                </form>
            </div>
        </div>
    </div>

</body>
</html>

DelaJob-Site-MVC/WebApplicationDelaJob/WebApplicationDelaJob/Views/Contato/Contato.cshtml
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DelaJob - Contato</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</head>
<body>

    <!-- Card cadastro: -->
    <div class="mt-5 mb-5">

        <div class="text-center">
            <h1 style="color: rgb(148, 84, 180);">Contato</h1>
        </div>

        <div class="card" style="margin: 0 auto; float: none; width: 42rem;">
            <div class="card-body" style="background-color: rgb(227, 229, 231);">
                <form>
                    <div class="form-inline mb-3">
                        <div class="form-group">
                            <label for="Nome" class="lead">Nome:</label><br>
                            <input type="text" name="Nome" id="Nome" class="form-control w-100" aria-describedby="textHelp" required>
                        </div>
                        <div class="form-group ml-auto">
                            <label for="E-mail" class="lead">E-mail:</label><br>
                            <input type="email" name="E-mail" id="E-mail" class="form-control w-100" aria-describedby="emailHelp" required>
                        </div>
                    </div>

                    <div class="form-inline mb-3">
                        <div class="form-group">
                            <label for="Fone" class="lead">Telefone:</label><br>
                            <input type="text" id="Fone" name="Telefone" class="form-control w-100" placeholder="Opcional">
                        </div>
                        <div class="form-group ml-auto">
                            <label for="Assunto" class="lead">Assunto:</label><br>
                            <input type="text" id="Assunto" name="Assunto" class="form-control w-100" required>
                        </div>
                    </div>

                    <div class="form-group ml-auto m">
                        <label for="Mensagem" class="lead">Mensagem:</label><br>
                        <textarea id="Mensagem" name="Mensagem" rows="7" class="form-control" placeholder="Digite aqui..." required></textarea>
                    </div>

                    <div class="row">
                        <a class="text-muted card-link ml-4" href="#"><p class="lead mt-3 mb-0" style="font-size: 14px;">Limpar Formulário</p></a>
                        <button type="submit" class="btn text-light w-25 ml-auto mr-4" style="background-color: rgb(148, 84, 180); font-size: 25px; border-radius: 10px;">Enviar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

DelaJob-Site-MVC/WebApplicationDelaJob/WebApplicationDelaJob/Views/Home/Index.cshtml
<html>
<head>
    <title>DelaJob</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Link CSS do Bootstrap: -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Links JavaScript do Bootstrap: -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</head>

<body>
    <!-- Carrossel de imagens: -->
    <div class="carousel slide" id="carouselSite" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselSite" data-slide-to="0" class="active" aria-label="Slide 1"></li>
            <li data-target="#carouselSite" data-slide-to="1" aria-label="Slide 2"></li>
            <li data-target="#carouselSite" data-slide-to="2" aria-label="Slide 3"></li>
        </ol>

        <div class="carousel-inner">

            <div class="carousel-item active">
                <img src="../Views/Images/Foto1(1).jpeg" class="img-fluid d-block w-100" alt="Simone de Beauvoir" />
            </div>
            <div class="carousel-item">
                <img src="../Views/Images/Foto4.jpeg" class="img-fluid d-block w-100" alt="Estee Lauder" />
            </div>
            <div class="carousel-item">
                <img src="../Views/Images/Foto1(3).jpeg" class="img-fluid d-block w-100" alt="Oprah Winfrey" />
            </div>

        </div>
        <a class="carousel-control-prev" href="#carouselSite" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
            <span class="sr-only">Voltar</span>
        </a>
        <a class="carousel-control-next" href="#carouselSite" role="button" data-slide="next">
            <span class="carousel-control-next-icon"></span>
            <span class="sr-only">Avançar</span>
        </a>
    </div>

    <!-- Texto e imagem (Quem Somos): -->
    <div class="row mt-5">

        <div class="col-5 ml-5 mt-4">
            <h1 class="display-3" style="color: rgb(148, 84, 180);">Quem Somos</h1><br>
            <p class="lead"><b>DelaJob é uma organização sem fins lucrativos, cujo principal propósito é melhorar a situação de vulnerabilidade socioecômica de mulheres de baixa renda, através da valorização profissional e empregabilidade. Por meio de programas de capacitação de mão de obra feminina, o DelaJob promove o empoderamento feminino e geração de renda.</b></p>
            <br>
            <p class="lead"><b>O projeto social foi fundado em 2022, através de um desafio proposto pela Recode Pro, tal iniciativa nasceu a partir de um grupo de 4 pessoas que se uniram para de sair de suas bolhas sociais e ver o mundo com outra perspectiva. Desse modo, criando uma rede de fortalecimento e pertencimento focada em mulheres em desemprego.</b></p>
        </div>
        <div class="ml-auto mr-auto">
            <img src="../Views/Images/img-home-delajob.jpg" style="width: 600px; height: 600px;">
        </div>

    </div>

    <!-- Texto e Cards com links: -->
    <div class="row mt-5">
        <div class="mt-5 pt-5">
            <h1 class="mt-3 col-6 ml-auto mr-auto text-center" style="color: rgb(148, 84, 180); font-size: 80px;">Vídeos e Palestras</h1>
        </div>
        <div class="col-2 mt-4">
            <a href="https://www.youtube.com/watch?v=-O99-J-dtr0" class="text-dark" type="button" target="_blank">
                <div class="card" style="background-color: FBC4C4; height: 400px;">
                    <img class="card-img-top" style="height: 150px;" src="../Views/Images/video1.png">
                    <div class="card-body">
                        <h4 class="card-title text-center">Mulheres brasileiras no Mercado de Trabalho</h4>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-2 mt-4">
            <a href="https://www.youtube.com/watch?v=6RSc_XYezig" class="text-dark" type="button" target="_blank">
                <div class="card" style="background-color: FBC4C4; height: 400px;">
                    <img class="card-img-top" style="height: 150px;" src="../Views/Images/video2.png">
                    <div class="card-body">
                        <h4 class="card-title text-center">Empoderamento das Mulheres</h4>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-2 mt-4">
            <a href="https://youtu.be/CiONvw9vvI0" class="text-dark" type="button" target="_blank">
                <div class="card" style="background-color: FBC4C4; height: 400px;">
                    <img class="card-img-top" style="height: 150px;" src="../Views/Images/video3.png">
                    <div class="card-body">
                        <h4 class="card-title text-center">Mulheres no Mercado de Trabalho | Entrevista - Futuro do Trabalho</h4>
                    </div>
                </div>
            </a>
        </div>
    </div>

    <!-- Mais textos e cards: -->
    <div class="row mt-5 ml-5 mb-lg-5">

        <div class="col-2 mt-4">
            <div class="card" style="background-color: FBC4C4; height: 400px;">
                <img class="card-img-top" style="height: 150px;" src="../Views/Images/medium-shot-woman-work.jpg">
                <div class="card-body">
                    <h3 class="card-title text-center">Tecnologia</h3>
                </div>
            </div>
        </div>

        <div class="col-2 mt-4">
            <div class="card" style="background-color: FBC4C4; height: 400px;">
                <img class="card-img-top" style="height: 150px;" src="../Views/Images/female-chef-chopping-vegetables-kitchen.jpg">
                <div class="card-body">
                    <h3 class="card-title text-center">Culinária</h3>
                </div>
            </div>
        </div>

        <div class="col-2 mt-4">
            <div class="card" style="background-color: FBC4C4; height: 400px;">
                <img class="card-img-top" style="height: 150px;" src="../Views/Images/happy-friendly-cashier-giving-credit-card-customer-after-payment-thanking-purchase-smiling-medium-shot-shopping-concept.jpg">
                <div class="card-body">
                    <h3 class="card-title text-center">Vendas</h3>
                </div>
            </div>
        </div>

        <div class="mt-5 pt-2 col-5 ml-auto mr-auto">
            <h1 class="mt-5 text-center" style="color: rgb(148, 84, 180); font-size: 80px;">Vagas em diversas Áreas</h1>
        </div>
    </div>

</body>
</html>

DelaJob-Site-MVC/WebApplicationDelaJob/WebApplicationDelaJob/Views/Login/Login.cshtml
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <title>DelaJob - Entrar</title>
</head>
<body>

    <!-- Card cadastro: -->
    <div class="mt-5" style="padding-bottom:110px;">

        <div class="text-center">
            <h1 style="color: rgb(148, 84, 180);">Login</h1>
        </div>

        <div class="card" style="margin: 0 auto; width: 18rem;">
            <div class="card-body" style="background-color: rgb(227, 229, 231);">
                <form>
                    <div class="form-group">
                        <label for="E-mail" class="lead">E-mail:</label><br>
                        <input type="email" name="E-mail" id="E-mail" class="form-control" aria-describedby="emailHelp" required>
                    </div>
                    <div class="form-group">
                        <label for="Senha" class="lead">Senha:</label><br>
                        <input type="password" name="Senha" id="Senha" class="form-control" required>
                    </div>

                    <div class="text-center">
                        <button type="submit" class="btn text-light w-50" style="background-color: rgb(148, 84, 180); font-size: 25px; border-radius: 10px;">Entrar</button>
                        <a class="text-muted card-link" href="#"><p class="mt-2 lead" style="font-size: 14px;">Esqueceu a senha?</p></a>
                        <a class="card-link" style="color: rgb(148, 84, 180);" href="#"><h2 class="lead">Cadastre-se</h2></a>
                    </div>
                </form>
            </div>
        </div>
    </div>

</body>
</html>

DelaJob-Site-MVC/WebApplicationDelaJob/WebApplicationDelaJob/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]DelaJob</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header style="background-color: rgb(148, 84, 180);">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark box-shadow">
            <a class="navbar-brand text-light col-7" asp-area="" asp-controller="Home" asp-action="Index"><img src="../Views/Images/whatsapp-logo-1.png"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Sobre" asp-action="Sobre">Sobre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Vagas" asp-action="Vagas">Vagas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Contato">Contato</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light border-left ml-4 pl-4" asp-area="" asp-controller="Login" asp-action="Login">Entrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Cadastro" asp-action="Cadastro">Cadastre-se</a>
                        </li>
                    </ul>
                </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div style="background-color: rgb(148, 84, 180);">
            <nav class="navbar navbar-expand-lg navbar-dark">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-lg-5">
                        <li class="nav-item mr-lg-5 ml-lg-5">
                            <a class="nav-link text-light" href="#">Políticas de Privacidade</a>
                        </li>
                        <li class="nav-item ml-lg-5 mr-lg-5">
                            <a class="nav-link text-light" href="#">FAQ</a>
                        </li>
                        <li class="nav-item ml-lg-5">
                            <a class="nav-link text-light" href="#">Termos de Uso</a>
                        </li>
                    </ul>
                </div>
                <a class="navbar-brand text-light col-3" href="#"><img style="height: 30px; width: 30px;" src="../Views/Images/whatsapp-logo-1.png"></a>
            </nav>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>